export const USER_LOGIN = 'USER_LOGIN';

export const REQUEST_API = 'REQUEST_API';

export const ADD_RECIPE_MEALS = 'ADD_RECIPE_MEALS';

export const ADD_RECIPE_DRINKS = 'ADD_RECIPE_DRINKS';

export const ADD_CATEGORY_MEALS = 'ADD_CATEGORY_MEALS';

export const ADD_CATEGORY_DRINKS = 'ADD_CATEGORY_DRINKS';

export const FAIL_API = 'FAIL_API';

export const REQUEST_DETAILS = 'REQUEST_DETAILS';
