export const mockFood = [{
  dateModified: null,
  idMeal: '52978',
  strMeal: 'Kumpir',
  strArea: 'Turkish',
  strCategory: 'Side',
  strDrinkAlternate: null,
  alcoholicOrNot: '',
  strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
  strInstructions: 'If you order kumpir in Turkey, the standard',
  strTags: 'SideDish',
  strIngredient1: 'Potatoes',
  strIngredient2: 'Butter',
  strIngredient3: 'Cheese',
  strIngredient4: 'Onion',
  strIngredient5: 'Red Pepper',
  strIngredient6: 'Red Chile Flakes',
  strMeasure1: '2 large',
  strMeasure2: '2 tbs',
  strMeasure3: '150g',
  strMeasure4: '1 large',
  strMeasure5: '1 large',
  strMeasure6: 'Pinch',
}];

export const mockDrinks = [{
  dateModified: null,
  idMeal: '15997',
  strDrink: 'GG',
  strArea: 'Turkish',
  strCategory: 'Ordinary Drink',
  strDrinkAlternate: null,
  alcoholicOrNot: '',
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
  strInstructions: 'Pour the Galliano liqueur over ice. Fill the remainder of the glass',
  strTags: 'SideDish',
  strIngredient1: 'Galliano',
  strIngredient2: 'Ginger ale',
  strIngredient3: 'Ice',
  strMeasure1: '2 1/2 shots',
}];

export const mockFavorite = [
  {
    id: '52977',
    type: 'food',
    nationality: 'Turkish',
    category: 'Side',
    alcoholicOrNot: '',
    name: 'Corba',
    image: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
    doneDate: '2022-08-27T07:33:48.720Z',
    tags: ['Soup'],
  },
  {
    id: '15997',
    type: 'drink',
    nationality: '',
    category: 'Ordinary Drink',
    alcoholicOrNot: 'Optional alcohol',
    name: 'GG',
    image: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
    doneDate: '022-08-29T02:02:50.823Z',
    tags: [],
  },
];
